const ALERT = "ALERT";
const REFETCH_CHATS = "REFETCH CHATS";

const NEW_ATTACHMENT = "NEW ATTACHMENT";
const NEW_MESSAGE_ALERT = "NEW MESSAGE ALERT";

export { ALERT, REFETCH_CHATS, NEW_ATTACHMENT, NEW_MESSAGE_ALERT };
